### ISSUE TITLE
I think your cocoapod is installing a previous version of this control

### ISSUE THREAD

**Issue by lunarbase** [edgurgel/CMNavBarNotificationView#12]
Just to let you know... Your cocoapod listed on cocoapods.org, is this

pod 'CMNavBarNotificationView', '~> 1.0'

Every time I install it, it installs an old version of this control. The version with UITextAlignmentLeft and 4 more issues.

**Comment by edgurgel** [comment]
Thanks for reporting. I will release a new version ASAP.

**Comment by edgurgel** [comment]
Just published a new version. Can you check if it fixes the issues for you?

**Comment by lunarbase** [comment]
Perfect now the correct version is installed but there is just a cosmetic issue: Cocoapods.org shows that this is version 1.05 but the command pod install shows that version 1.0.4 was installed. Anyway, thanks for the fast response.

**Comment by edgurgel** [comment]
Great! :+1:
